import { Component, OnInit, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'todo-input',
  template: `
  <input class="todo-input"
      [value]="title"
      (keyup.enter)="changeTitle($event.target.value)"
      #inputElement>
<button class="btn" (click)="changeTitle(inputElement.value)">
  Save
</button>
`,
  styleUrls: ['./input.component.css']
})
export class InputComponent implements OnInit {
  
  title: string='my title';
  @Output() submit: EventEmitter<string> = new EventEmitter();

  constructor() { 
    this.changeTitle ('this is my title');
    console.log('in constructor');
    this.changeTitle('I love Angular');
    console.log(this.title);
  }

  ngOnInit() {
    console.log('in constructor');
    this.changeTitle('title');
    console.log(this.title);
  }

  changeTitle(newTitle: string): void {
    console.log(newTitle)
    this.submit.emit(newTitle);
  }

  generateTitle(): string {
  return 'This title was generated by a method.';
}
}